using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class WoodManager : MonoBehaviour
{
    // para a単adir canvas public GameObject imagenLlave;
    void OnTriggerEnter(Collider c){
        if (c.gameObject.CompareTag("Madera")){
            //1. Desaparece la llave
            Destroy(c.gameObject);
            //2. Aparece en la interfaz de usuario
            // A単adir canvas imagenMadera.SetActive(true);
            //3. A単adimos al inventario
            GetComponent<Inventario>().AddItem(c.gameObject); // a単adir llave inventario
        }
    }
}
